apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:1.0.0
        args:
        - "-text=Hello from the Secure Backend API v1!"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
  selector:
    app: backend-app
