apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mtls
  namespace: default
spec:
  mtls:
    # Allows both encrypted mTLS and unencrypted plain-text traffic
    mode: PERMISSIVE

